### ISSUE TITLE
[bug] `<rh-footer>` emits warning about links set without a valid header

### ISSUE THREAD

**Issue by krisahil** [RedHat-UX/red-hat-design-system#2259]
### Describe the bug

When we render <rh-footer>, it always emits this warning in the browser console:
```
logger.ts:77 [rh-footer-links] This links set doesn't have a valid header associated with it.
```

This happens even on the standalone demo: https://ux.redhat.com/elements/footer/demo

Why does it emit this warning? How can we fix its cause?

### Screenshots

<img width="1484" alt="Image" src="https://github.com/user-attachments/assets/64978374-1e9b-4e1d-9470-2c7a4f4aa5a7" />

### Steps to reproduce

1. Go to https://ux.redhat.com/elements/footer/demo/
2. Observe the warning in the browser console.

### Expected behaviour

There is no warning emitted about <rh-footer>.

### Element HTML

```HTML

```

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
@krisahil do you still observe those logs? Perhaps this has already been resolved in the 3.x release?

**Comment by krisahil** [comment]
I'm still seeing the error on https://ux.redhat.com/elements/footer/demo/ (which I assume is running the 3.x release?).

<img width="1110" alt="Image" src="https://github.com/user-attachments/assets/52b76158-81a7-4a7d-8013-0218f1f14af4" />

**Comment by markcaron** [comment]
@krisahil @bennypowers, I believe the original intent was to ensure that every list of links had a heading (an accessibility requirement).

However, it seems the [code doing the check ](https://github.com/RedHat-UX/red-hat-design-system/blob/55a10b6cde614f3025f87d130e8798f57a7c5250/elements/rh-footer/rh-footer-links.ts#L40C40-L40C55)is looking for a `slot="header"` which isn't being used. Instead, the header is being slotted inside the `links` slot. Not sure what happening internally, as it seems to me (and my limited knowledge of this component), that it's not even using `rh-footer-links` properly?

Perhaps @heyMP knows?

**Comment by bennypowers** [comment]
NB: We've set a broader goal to remove these logs from element classes, and instead have sites use HTML analysis tools to determine if their usage of RHDS is correct
